language: python
python:
  - "2.7"

sudo: enabled

script:
  - make

before_install:
  - npm install -g less request
  - wget https://github.com/viur-framework/pyjs/archive/0.8.1a.tar.gz
  - tar xvfz 0.8.1a.tar.gz
  - pushd pyjs-0.8.1a && sudo make system-install && popd
  - touch *
  - git submodule init && git submodule update
 
